### ISSUE TITLE
Inpaint Overlap

### ISSUE THREAD

**Issue by XpucT** [richrobber2/canvas-zoom#1]
Hey 🖐
First of all ➜ Thank you for great solution!

The problem:
![When you click on the result image, you can see the overlap from the left side](https://i.imgur.com/tr8w8pY.gif)

**Comment by richrobber2** [comment]
i could have it scroll down when clicking on the image cause its using absolute values and the popup is using sticky so u should just be able to scroll down to see it better

**Comment by richrobber2** [comment]
fixed by commit #2 now you can press o to to toggle overlay

other changes can be seen on readme on  main github repo
