### ISSUE TITLE
Can't change the hotkeys

### ISSUE THREAD

**Issue by personxyz** [richrobber2/canvas-zoom#18]
Every time I right click and select change hotkeys from the menu nothing happens. When I try any of the hotkeys they don't do anything either. 

I have the latest WebUI installation so I don't know what I'm doing wrong tbh. I thought that if I'd messed something up right clicking wouldn't bring up the context menu but it does. It's just that nothing else seems to work.

**Comment by daswer123** [comment]
Hi, do you mean this?
![image](https://user-images.githubusercontent.com/22278673/229310367-cdd326f2-9553-4b15-965f-8bde8e66c62b.png)
This is not a functional item, it's just a table of contents, try to click on any hotkey in this menu and you'll get a window suggesting you change the hotkey to the one you want

**Comment by daswer123** [comment]
https://user-images.githubusercontent.com/22278673/229310720-f440dff6-2875-4b0b-9a23-5f872706e5a7.mp4

**Comment by personxyz** [comment]
Lol, sleep deprivation is catching up to me I guess. Thanks for the prompt reply and video. 

How do I actually zoom though, I assume 'Shift + wheel' is the correct hotkey? What does wheel mean, the actual mouse wheel? I don't use a mouse as I'm on a laptop, can I change this to something else?

**Comment by daswer123** [comment]
@personxyz 

> How do I actually zoom though, I assume 'Shift + wheel' is the correct hotkey? What does wheel mean, the actual mouse wheel? I don't use a mouse as I'm on a laptop, can I change this to something else?

Not yet, there's no way to change that. 
I will try to implement it in the next few days. 
If it will be implemented on the + and -, will it be okay?

What do you think, if it is implemented on + and -, will it be okay?

**Comment by personxyz** [comment]
Thanks, I look forward to it!

As for which button to use, z for zoom seems the obvious choice I guess. Maybe e for enhance or m for magnify.

**Comment by personxyz** [comment]
The + and - keys could work too, although it couldn't be Ctrl and + because that's how you zoom in on web pages (at least on chrome so they might clash).

**Comment by daswer123** [comment]
Good idea, I think I will bind + and - to the shift, similar to ctr + and ctr -

**Comment by personxyz** [comment]
Sounds perfect, I'm looking forward to trying it out!

**Comment by daswer123** [comment]
> Sounds perfect, I'm looking forward to trying it out!

While this is a pull request you can try out the changes in my fork, https://github.com/daswer123/canvas-zoom

**Comment by personxyz** [comment]
Damn, that was super quick. Thanks for the hard work! I'll have a try some time tomorrow when I get a chance, inpainting is the main thing I use in stable diffusion so I'm really excited to try this.

**Comment by daswer123** [comment]
> Damn, that was super quick. Thanks for the hard work! I'll have a try some time tomorrow when I get a chance, inpainting is the main thing I use in stable diffusion so I'm really excited to try this.

It's cool that you liked it.

Listen, there's a question, do you think it makes sense to overlap during previews, or is it better to turn it off?

https://user-images.githubusercontent.com/22278673/229370506-6526a4a7-dcbb-43d3-8af1-dee9d0b115c7.mp4

**Comment by personxyz** [comment]
I personally don't think I'd use an overlap feature but others might as it's useful for performing a more detailed 'before' and 'after' comparison to see the changes made as the images are enlarged. 

If I'm comparing stuff I usually just right click on the images and select 'Open image in new tab' and then shift between the tabs. This opens them at full resolution and left clicking on them zooms in even further. That's good enough for me but not everyone will be aware of that option so your method could be helpful. 

Ultimately if you can make it possible to turn on and off people can decide for themselves whether it's useful for their workflows.

**Comment by daswer123** [comment]
> I personally don't think I'd use an overlap feature but others might as it's useful for performing a more detailed 'before' and 'after' comparison to see the changes made as the images are enlarged.
> 
> If I'm comparing stuff I usually just right click on the images and select 'Open image in new tab' and then shift between the tabs. This opens them at full resolution and left clicking on them zooms in even further. That's good enough for me but not everyone will be aware of that option so your method could be helpful.
> 
> Ultimately if you can make it possible to turn on and off people can decide for themselves whether it's useful for their workflows.

Thanks for the opinion, it was interesting to hear.

**Comment by personxyz** [comment]
No problem, thanks for being so open to feedback and passionate to improve. That's a great attitude to have in life.
