### ISSUE TITLE
Such a very useful extension, even if still a bit flawed

### ISSUE THREAD

**Issue by hansolocambo** [richrobber2/canvas-zoom#21]
- Shift + Left or Right click to pan : generates a brush stroke. Can be deleted thanks to the very useful Ctrl+Z, and avoided if one has some empty spots around the image to click on before panning.
- Zooming in doesn't bring the image to full foreground. So it stays behind a lot of the User Interface elements. Especially the generated image on the right. 
![2023_04_03_00_16_29_Stable_Diffusion_Mozilla_Firefox](https://user-images.githubusercontent.com/33687288/229381979-682a2cd4-4929-414f-944b-becad86dc714.jpg)
- Ctrl+Wheel : constantly resets the brush to the center of the image, no matter where was the mouse's cursor.

Small things, quiet annoying. But all in all it's already great.

**Comment by daswer123** [comment]
Hi @hansolocambo, thanks for sharing your experience, almost all the problems you described have already been solved, look 

1) You can use the context menu to toggle the move mode so you can move canvas to the button (default: F)

https://user-images.githubusercontent.com/22278673/229382390-4a608993-909b-47bb-9e64-f62af8662d46.mp4


2) You can turn on the overlapping of all elements (default: O) and you won't get in the way.

https://user-images.githubusercontent.com/22278673/229382404-cdcd1423-a331-42f8-81b9-96f497b69079.mp4


3) Sorry, I can't do anything about a brush that is centered, the behavior is set by a python script, canvas-zoom is a JS script.

You can reassign any hotkey via the context menu

**Comment by hansolocambo** [comment]
Wow absolutely amazing. Sorry about the non-bug report then ;) I totally missed that menu you make appear here in the videos. That's really cool indeed.
Thanks a lot daswer123  (b^-^)b

**Comment by daswer123** [comment]
Cool, good observation, now checked and it is true if you right click on the mouse with shift, the firefox menu appears. 

I have it so that if you accidentally right click, the menu disappears quickly, just hover over it and choose as much as you want.

You don't have to hold the shift for the contex menu, just right click once. For the other hotkeys too, they work without the shift in the image area.


https://user-images.githubusercontent.com/22278673/229462665-6798706c-bda5-4f14-a832-b8ddc5e5ce66.mp4

**Comment by richrobber2** [comment]
interesting, also looks like all your problems where solved anything else? @hansolocambo

**Comment by richrobber2** [comment]
i will take it that that is all closing
