### ISSUE TITLE
Context menu not working on some browsers

### ISSUE THREAD

**Issue by zvit** [richrobber2/canvas-zoom#24]
Context menu works in Incognito mode, on Vivaldi, and other clean browsers. But won't work on browsers with extensions (which most of us use), like Chrome, and Opera. I've tried disabling many extensions, but it still won't pop up.

**Comment by daswer123** [comment]
Hi, I don't know what extensions you use, but I have about 15 extensions of different orientation in Edge and Crome, everything works and nothing interferes with the appearance of the context menu.

In Firefox, Opera also works, although I do not use these browsers and I do not have extensions there.

Perhaps one of the extensions blocks the context menu, and if you know which one, I would be very grateful to know which one.

**Comment by zvit** [comment]
I'll definitely play around and find the ones causing it, and update here.

**Comment by Gloynus** [comment]
У меня в Яндекс.Браузере и Эйдже вообще ничего не работает. В том числе, проверял с выключением всех браузерных расширений. Ни горячие клавиши, ни контекстное меню.

**Comment by daswer123** [comment]
@Gloynus Привет, проверь версию webui, если у тебя другой commit hash, то обнови webui вручную, через git pull. 
![image](https://user-images.githubusercontent.com/22278673/231105235-fddb280c-d855-4947-a841-dea8d0ef9cc8.png)

Сам сижу через Edge :)

**Comment by Gloynus** [comment]
Да, хэш отличается. Но мне казалось, что строчка git pull origin master должна обновлять Стейбл при запуске. Нет?
![image](https://user-images.githubusercontent.com/121782978/231284308-0f45aa16-aea6-44c0-915e-ad727da335b2.png)
![image](https://user-images.githubusercontent.com/121782978/231284921-e05d490f-c9f3-4d04-846c-2a355484d49b.png)

**Comment by daswer123** [comment]
![image](https://user-images.githubusercontent.com/22278673/231287712-296e68cf-2727-4186-987a-6a64dd4443b8.png)

Видимо другие extension как-то затронули эти файлы, поэтому и не обновляется.

**Comment by Gloynus** [comment]
@daswer123 Это действительно помогло — расширение заработало. Благодарю.
Правда теперь в консоли много непонятной мне ругани. Возможно, вам известно как и её починить?
![image](https://user-images.githubusercontent.com/121782978/231309292-07a738cf-9d67-4661-9655-ab69ecfe3297.png)

**Comment by daswer123** [comment]
@Gloynus 
Если текст в консоли желтого цвета, то это от webui, если красного и указанно, что ошибка от canvas-zoom, то кидайте скриншот, попробую разобраться.

![image](https://user-images.githubusercontent.com/22278673/231317726-da875494-4a8d-4a1b-b539-3e4a330374dd.png)

**Comment by daswer123** [comment]
@zvit If you have any information about the expansion, create a new issue.
