### ISSUE TITLE
Change the hot keys more consistently

### ISSUE THREAD

**Issue by pvp-by** [richrobber2/canvas-zoom#25]
**T** = **T**ranparent (now it C)
ctrl/shift + T (now it V)
**Q** = **Q**uick color
**С** = **C**olor

**Comment by daswer123** [comment]
Hi @pvp-by, you can customize any hotkeys you want via the context menu.
Right-click on the image area.


https://user-images.githubusercontent.com/22278673/231013880-8d6e7ee4-07bb-4008-bdb8-dbf58c17374c.mp4

**Comment by pvp-by** [comment]
@daswer123 excellent, then it is probably worth adding this information to the readme

**Comment by daswer123** [comment]
@pvp-by already
![image](https://user-images.githubusercontent.com/22278673/231131280-9b29749d-87a4-43ad-979e-26c0a3c3930e.png)

**Comment by pvp-by** [comment]
my bad, Maybe you could save the settings to a file so that you can transfer them.

**Comment by daswer123** [comment]
Good idea, I think I will make it possible to edit hotkeys in a separate file so that it can be transferred to another person

**Comment by pvp-by** [comment]
Thanks for the work done and future updates!

**Comment by daswer123** [comment]
@pvp-by Done. Now you can customize the hotkeys in the customHotkeys.js file, and then load them in the context menu. You can pass this file to anyone and they will be able to use your hotkeys settings.
