### ISSUE TITLE
I can't get this to work on any browser

### ISSUE THREAD

**Issue by ManOrMonster** [richrobber2/canvas-zoom#26]
- No context menu or shortcut keys work. 
- I have tried Edge, Chrome, Brave, and Vivaldi. I don't have add-ons installed in anything but Edge.
- I have tried deleting and reinstalling the extension.
- I have only installed it via the official list.

<img width="506" alt="image" src="https://user-images.githubusercontent.com/3925151/231284131-a8f753db-5d46-44ff-b979-cd9dffbb0065.png">

<img width="810" alt="image" src="https://user-images.githubusercontent.com/3925151/231284191-60bbef9e-4e6b-4d51-b4ba-413c2e9b5c4d.png">

I also removed all extensions but this one, same issue:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/3925151/231285809-4549aa25-a306-428c-ab34-d0b7f2cef810.png">

I get tons of these errors in the console. Not sure what's causing them (not this extension), but maybe they have something to do with it not working:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/3925151/231287041-feb49d99-f1f4-4046-8a2e-21d39bdb391c.png">

I'm not sure what else to check.

**Comment by daswer123** [comment]
@ManOrMonster Try running in a collab

https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb#scrollTo=CFWtw-6EPrKi

Don't check this box
![image](https://user-images.githubusercontent.com/22278673/231304960-4cae1e72-b0d1-40e1-8862-9a5f6637cdd0.png)

So we can check if it's the computer or something else

**Comment by ManOrMonster** [comment]
@daswer123 Just tried in Edge, Brave and Vivaldi with the collab, same issue.

**Comment by ManOrMonster** [comment]
@daswer123 It's just JS, what the heck could be the problem? I don't have any browser add-ons installed for Vivaldi or Brave, can't be that.

Here's my collab, does it work for you? https://strips-rising-outcomes-mexican.trycloudflare.com/

**Comment by daswer123** [comment]
@ManOrMonster 👍

**Comment by richrobber2** [comment]
lol gotta love when that happens
