### ISSUE TITLE
Can't install AssertionError: extension access disabled because of command line flags

### ISSUE THREAD

**Issue by greqov** [richrobber2/canvas-zoom#29]
Hello!
I get an error `AssertionError: extension access disabled because of command line flags` when I'm trying to install this extension. I guess it's because of AMD video card but have to try luck anyways.
So because of AMD card I use [lshqqytiger's fork](https://github.com/lshqqytiger/stable-diffusion-webui-directml) to run SD. Commands line flags are:
```cmd
set COMMANDLINE_ARGS=--listen --medvram --precision full --opt-split-attention-v1 --no-half --no-half-vae --opt-sub-quad-attention --disable-nan-check --use-cpu interrogate gfpgan bsrgan esrgan scunet codeformer
```
End of log:
```cmd
Error completing request
Arguments: ('https://github.com/richrobber2/canvas-zoom.git', ['ads', 'localization', 'installed'], 0, 'canvas') {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui-directml\modules\ui_extensions.py", line 178, in install_extension_from_index
    ext_table, message = install_extension_from_url(None, url)
  File "D:\stable-diffusion-webui-directml\modules\ui_extensions.py", line 133, in install_extension_from_url
    check_access()
  File "D:\stable-diffusion-webui-directml\modules\ui_extensions.py", line 21, in check_access
    assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
AssertionError: extension access disabled because of command line flags
```
Maybe you have some thoughts how it can be fixed?

**Comment by daswer123** [comment]
@greqov 
Remove --listen flag, install extension and you can add flag again

![Screenshot_2023-04-17-12-21-46-46_c0dc27f5c07cb0fb3541d6073dfd6932](https://user-images.githubusercontent.com/22278673/232442250-e6a1440a-23a7-48db-9c73-7b5b6c22f990.jpg)

**Comment by daswer123** [comment]
I hope it worked, if there is still a problem, write here, I will reopen this issue
