### ISSUE TITLE
Could it work inside ControlNet canvas?

### ISSUE THREAD

**Issue by Andrey36652** [richrobber2/canvas-zoom#32]
As for now it works in Inpaint and Inpaint sketch, but does not in ControlNet canvas.

**Comment by daswer123** [comment]
Hi, I don't use controlNet much. Doesn't drawing inside a controlNet canvas break the result?

**Comment by Andrey36652** [comment]
@daswer123 
I don't know. I've installed controlnet just 2 ays ago. But I think drawing inside controlnet canvas (like scribble) should be legit, otherwise why did they implemented it?

**Comment by daswer123** [comment]
Checked it now, and it still breaks if you draw. 

https://user-images.githubusercontent.com/22278673/233673982-e747734c-82ce-454d-aedf-8082ab0abd03.mp4

**Comment by daswer123** [comment]
When you draw, it doesn't remember the original result and only draws what you drew over the picture.

https://user-images.githubusercontent.com/22278673/233675446-982c0155-4a3b-4fe5-8134-a26c53c4fb19.mp4

**Comment by Andrey36652** [comment]
@daswer123 hm, okay. Thank you
