### ISSUE TITLE
Adding support to bind mouse middle click and side buttons

### ISSUE THREAD

**Issue by Zullian** [richrobber2/canvas-zoom#33]
I love the extension, but I'd like to use undo button on mouse button 4, atm I can't set it, I even tried to modify hotkeys file but it didn't work. Also full screen/reset would be nice if it could be on same button like "O - Overlap all elements and back".

**Comment by daswer123** [comment]
@Zullian 
Hi, thanks for the ideas.
Recently updated, you can check :)

**Comment by daswer123** [comment]
Look, first you open the file customHotkeys.js in any editor, edit the hotkeys as you want, then reload the webui page and the upload from the file will work

https://user-images.githubusercontent.com/22278673/233824866-dad188b9-4571-469c-b1fc-9de918d8b874.mp4

**Comment by daswer123** [comment]
A little more about additional mouse buttons ( button 3 or button 4 ) while undo works for any additional button of the mouse, I think in the future redo the system change hottkeys and add the ability to customize more convenient than now
