### ISSUE TITLE
Context Menu unreadable in Dark Mode

### ISSUE THREAD

**Issue by SlippyTheToad** [richrobber2/canvas-zoom#37]
As the title says, when switched into Dark Mode the text of the context menu becomes unreadable. 

![image](https://user-images.githubusercontent.com/11802054/235421892-fca337dc-43c5-4428-818e-a9a81cb90cf0.png)

I first noticed this issue when using the Kitchen theme, but it persisted when disabling the them and changing between light and dark mode. 

This can be alleviated by making a few changes to **canvas-zoom.js** and **style.css** requiring a separate set of style rules for dark mode. 

**In canvas-zoom.js line 354 change:**

`menu.className = "context-menu";`

**to**

```
/* the light theme uses rgba while dark uses rgb, this is absolutely a hack */
menu.className = (getComputedStyle( document.querySelector("body") ).backgroundColor.includes('rgba')) ? "context-menu cm-light" : "context-menu cm-dark";
```

This will check the body class for the light or dark class and set the appropriate class style for our mode.

**Then in style.class change the following:** 

```
.context-menu {
  display: none;
  position: absolute;
  background-color: #ffffff;
  border: 1px solid #ccc;
  padding: 8px;
  z-index: 1000;
  font-size: 14px;
}

.context-menu ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
}

.context-menu li {
  font-size: 12px;
  padding: 4px 6px;
  cursor: pointer;
}

.context-menu h3 {
  font-size: 14px;
  margin: 0;
  padding: 4px 8px;
}

.context-menu li:hover {
  background-color: #f1f1f1;
}
```

**change to:** 

```
/* Context Menu */
.context-menu {
  display: none;
  position: absolute;
  border: 1px solid #ccc;
  padding: 8px;
  z-index: 1000;
  font-size: 14px;
}

.context-menu ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
}

.context-menu li {
  font-size: 12px;
  padding: 4px 6px;
  cursor: pointer;
}

.context-menu h3 {
  font-size: 14px;
  margin: 0;
  padding: 4px 8px;
}

/* Light Theme Options */
.cm-light {
  background-color: #fff;
  color: #000;
}

.cm-light li:hover {
  background-color: #f1f1f1;
  color: #000;
}

/* dark theme options */
.cm-dark {
  background-color: #000;
  color: #fff;
}

.cm-dark li:hover {
  background-color: #fff;
  color: #000;
}
```
This will allow canvas-zoom's context menu to respect the theme and maintain visibility.

With the changes you'll see it act more like 
![image](https://user-images.githubusercontent.com/11802054/235431512-07a6990e-8f42-4b42-abc7-bdb74bad5398.png)
![image](https://user-images.githubusercontent.com/11802054/235431599-56ad34db-5887-496e-b915-df6b4f5bd7cc.png)

**Comment by daswer123** [comment]
@SlippyTheToad 
Hi, thanks for the edits. Already made the commit, you can update.
I made the colors less contrasty, which would be less harmful to the eyes
