### ISSUE TITLE
The latest version is unable to launch again.

### ISSUE THREAD

**Issue by Physton** [richrobber2/canvas-zoom#40]
I previously submitted a pull request that addressed the issue of failure to launch in my environment:
【There are two issues on my computer that caused the failure to launch. #35】
In the latest version, line 37 is missing "dist", which is causing it to fail to launch again.
![](https://oss-img.physton.com/2023/05/03/6452820f0c704.png)
Please fix it in a timely manner. Thank you!

**Comment by daswer123** [comment]
Hi, thanks for letting me know, when I was rewriting for the new version, I forgot to write in the code :)
