### ISSUE TITLE
some update broke the zoom function and inpainting alltogether

### ISSUE THREAD

**Issue by JaysonPhoenix** [richrobber2/canvas-zoom#44]
with some recent update inpainting broke when this extension is enabled, was away for some days and before the extension worked fine but when i came back and updated everything (except for torch 2) it didnt work anymore. 

when i upload or drag and drop a picture to the inpainting canvas the whole canvas disappears, same on sketch and inpaint sketch (not on inpaint upload tho). after fiddeling around forever i got it to show the canvas once and when it did the zoom didnt work (neither key nor wheel) but the rightclick menu worked fine, couldnt reproduce it tho since i couldnt get the inpainting canvas to stay after pic upload. as soon as i disable this extension everything works again.

so since i would expect everybody to use this extension and i see no issue reports here, is it only me and some conflict or something missing or did some update break this extension? either way i need a fix or workaround asap since this extension became essential to me, so can somebody confirm or tell me its me and possibly come up with an idea whats wrong?

**Comment by daswer123** [comment]
Hi, this is an old bug. Update the extension and everything should be fine

**Comment by jeanpierre8** [comment]
yes, i have the same error, and after the update it's broken:
I have this version of the extension:
![image](https://user-images.githubusercontent.com/63020043/236789359-5019d4a1-5275-4081-a87b-91fd6fb89464.png)

**Comment by daswer123** [comment]
That's right, your version is from April 7. Click check for updates in the extension tab

**Comment by daswer123** [comment]
If the button does not update the extension, go to the extension folder, delete the canvas-zoom folder, and install it again through the extension tab

**Comment by jeanpierre8** [comment]
> If the button does not update the extension, go to the extension folder, delete the canvas-zoom folder, and install it again through the extension tab

Thanks, It's working !!!
Yes, I delete the extension and reinstall it because it doesn't update when I click to check for updates in the extension tab

**Comment by JaysonPhoenix** [comment]
interesting. yes that fixed it for me too and i had the same version as he had. but it was saying thats already the latest version, how would i know its not to prevent that in the future? or was that some one time thing and it just hasnt been mentioned at the front page here that that specific version has to be updated manually by deleting and reinstalling? would probably help if the front page would state the latest release version number and date too for the chance i would have had the idea its lying about it beeing up to date. anyway, thx for the help ;)
