### ISSUE TITLE
can you make your extension work on other extension canvas too?

### ISSUE THREAD

**Issue by JaysonPhoenix** [richrobber2/canvas-zoom#47]
i stumbled upon a situation where youre zoom feature and stuff would help too so, can you make your features work on other extensions canvas or maybe every canvas in general too? in my case its the regional prompter extensions "draw a mask region" canvas thats pretty small, and even tho it has already been adressed and will becoming a bit bigger in i guess the next update its still limited by the web ui extensions row which is the same problem for all extensions canvas, like controlnet for example which also has a too smal canvas to properly draw on if needed now. so would it be possible to make your zoom and hotkey stuff work on such canvas too, maybe by making it work on every canvas in general? i have no idea about the code so im just asking if it would work that way around.

**Comment by daswer123** [comment]
This would be problematic because in most cases canvas appears after you click on an extension tab (e.g. ControlNet, Regional Prompter, etc.) and since they are not in webui right away I can't connect to them. I can add support for extensions like I did before with ControlNet

**Comment by daswer123** [comment]
Hi, added integration with the regional prompter today, update and turn it on in the settings.
