### ISSUE TITLE
Pipette does not grab color exactly where cursor is on top of.

### ISSUE THREAD

**Issue by ryenots** [richrobber2/canvas-zoom#48]
From what I can tell, the pipette / eyedropper color grabbing feature does not grab the color exactly where the crosshair is on top of. Instead, it grabs color from the right(?) of the crosshair somewhere. I have not provided an example of reproducing this, because it seems simple to reproduce. If you cannot see the issue I am talking about, I am happy to provide an example.

**Comment by daswer123** [comment]
Thank you for reporting the problem.
I will look into it and fix it soon.

I can't deal with it right now because I have work stuff to do.

**Comment by daswer123** [comment]
I shifted the dropper 1 pixel to the left, it seems to work correctly.

**Comment by ryenots** [comment]
I've updated the extension, and I am still seeing what I feel is the issue. Perhaps I am misinterpreting how the eyedropper tool is supposed to work. Here's an example:

![ex](https://github.com/richrobber2/canvas-zoom/assets/48464025/88cdbac4-a4b3-4225-a85d-3d056f501d57)

Should all of eyedropper samplings in this gif not be a shade of green? The color is clearly being taken from the bottom right of where the crosshair is positioned. Let me know if I am not understanding how this tool should work. I've also attached the image I am testing this with. Thanks

![test_img](https://github.com/richrobber2/canvas-zoom/assets/48464025/bf4fabca-6bc4-45a4-838a-98657b4a5d23)

**Comment by daswer123** [comment]
Thanks for the picture, I have some time, I will fix it soon

**Comment by daswer123** [comment]
Now I checked with myself and it works fine for me

https://github.com/richrobber2/canvas-zoom/assets/22278673/12798cf4-dadc-48ba-add1-89d22c19e756

**Comment by ryenots** [comment]
I've discovered this issue is a difference in browsers. I am using Firefox, which is where the issue is present. Chrome does not have this issue, I have not tested any other browsers than these two. I am using Windows as well, however I don't think this has to do with operating systems.

**Comment by daswer123** [comment]
Firefox is causing the problem again, thanks for letting me know.
