### ISSUE TITLE
Erasing

### ISSUE THREAD

**Issue by SharapaGorg** [richrobber2/canvas-zoom#49]
Every time my ass burns with the fact that when you press enter, everything is erased, and also that when you press the eraser, absolutely the entire mask is erased, every time I think that when I press the eraser, I can erase the mask in the right places, but all my fucking mask wears off and I sink into an endless depression. In fact, I have not even figured out if the eraser button is the functionality of your extension, but if you can change it, **THEN PLEASE DO IT**

**Comment by daswer123** [comment]
This button came from the updated gradio, this extension has nothing to do with this button.

You can edit user.css (if you don't have it, create a file in the root folder of stable-diffusion)
and write at the end
```
button[aria-label="Clear"] {
	display: none;
}
```

**Comment by daswer123** [comment]
I hope this helped you.
