### ISSUE TITLE
errors and broken right click

### ISSUE THREAD

**Issue by imacopypaster** [richrobber2/canvas-zoom#5]
![image](https://user-images.githubusercontent.com/45368535/227789081-3eb6ec1f-698c-4dd3-8e2b-5a31787e9537.png)
The canvas-zoom extention causes an error in the browser console. **And most importantly: blocks the right mouse click on the entire web interface!**

**Comment by daswer123** [comment]
You may not have an updated automatic11, this canvas-zoom only works on recent updates.

The fix is already in the pull request, Waiting for aprove the pull request.

**Comment by imacopypaster** [comment]
@daswer123 
WebUI updated a week ago.
Well, let's wait until the author accepts pull request.

**Comment by daswer123** [comment]
WebUI must be from Mar 25, 2023 or later.

https://github.com/richrobber2/canvas-zoom/tree/33b690c2ccec1bf436d4d37af1c6998209a860b6
This commit should work on an older version of the WebUI, which was earlier than March 25 before the gradio update.

**Comment by richrobber2** [comment]
i assume this was fixed by daswer123 right? can it be closed?

**Comment by daswer123** [comment]
Yes, you can close
