### ISSUE TITLE
copy/paste images to canvas functionality breaks with plugin

### ISSUE THREAD

**Issue by codythomas** [richrobber2/canvas-zoom#50]
I was previously able to copy paste from photoshop, chrome, etc. The new canvas seems to not like Copy/Paste in Windows 11/ Chrome at least.

**Comment by daswer123** [comment]
If you disable the extension and reload webui copy/paste does it work?

**Comment by codythomas** [comment]
after more testing I found steps to reproduce reliably:

1.  img2img tab > inpainting
2. paste an image (works fine in this case)
3. zoom the canvas with shift + mousewheel
4. draw on canvas
5. try to paste a new image -> image is not pasted
6. reset zoom with R
7. try to paste a new image -> image is not pasted
8. switch focus with browser tabs or alt tab
9. try to paste a new image -> image is now _usually_ pasted as expected

- sometimes I have to fiddle with the canvas, window focus, or try copy/pasting a different image to get step 9 to actually work
- sometimes copy/paste completely breaks and I am unable to use it unless I reload the tab
- drag and drop / click to upload remains functional as a workaround

**Comment by daswer123** [comment]
I'm using Win10 and my copy/paste doesn't work at all, I checked with pure webui and with extension, it doesn't work at all.

**Comment by codythomas** [comment]
I'm on win11/chrome and use copy/paste a lot in my workflow without problems on vanilla webUI. It also does work with this extension, just not consistently

**Comment by daswer123** [comment]
Hi, I was recently testing the copy/paste functionality and found that it works.

But it only works outside of the canvas editing area. I checked with webui 1.4

**Comment by daswer123** [comment]
Hi, the latest update fixed this problem.
