### ISSUE TITLE
What kind of question is that？

### ISSUE THREAD

**Issue by gyy0611** [richrobber2/canvas-zoom#51]
Error running install.py for extension E:\novelai-webui-aki-v3\extensions\canvas-zoom.
Command: "E:\novelai-webui-aki-v3\py310\python.exe" "E:\novelai-webui-aki-v3\extensions\canvas-zoom\install.py"
Error code: 1
stdout: <empty>
stderr: 

-------------------------------------------------------------------------------

install.py 4 <module>

import gradio

__init__.py 3 <module>

import gradio.components as components

components.py 22 <module>

import matplotlib.figure

figure.py 43 <module>

from matplotlib import _blocking_input, backend_bases, _docstring, projections

__init__.py 58 <module>

from mpl_toolkits.mplot3d import Axes3D

__init__.py 1 <module>

from .axes3d import Axes3D

axes3d.py 45 <module>

class Axes3D(Axes):

axes3d.py 718 Axes3D

set_zticklabels = _axis_method_wrapper(

_base.py 57 __init__

doc = inspect.getdoc(getattr(maxis.Axis, method_name))

AttributeError:
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

type object 'Axis' has no attribute '_set_ticklabels'

**Comment by daswer123** [comment]
Honestly, I don't know what the mistake could be. 

There was a PR earlier, with a similar webui to yours. #35

**Comment by daswer123** [comment]
I hope this helped you, if there are problems, write a new issue
