### ISSUE TITLE
Can't zoom out (2)

### ISSUE THREAD

**Issue by fantomac** [richrobber2/canvas-zoom#57]
Hi, thanks.
Zoom out don't work, test on safari and chrome.
A open the dropper next to the icon, but after pressing T, A act like T
Ctr-Z or ALT-Z or OPTION-Z = nothing

![Capture d’écran 2023-05-25 à 11 11 27](https://github.com/richrobber2/canvas-zoom/assets/24393913/f5c4d313-f482-438d-8770-a7bd286181f3)

**Comment by daswer123** [comment]
Hmm, apparently Mac has its own specifics. I unfortunately do not have one and can not check it.

You can alternatively use Fullscreen mode "S" .

Ctr+Z do not know why it does not work, added support in the script.

What would return the color menu back, you just need to click on the button on the top right

**Comment by daswer123** [comment]
I hope everything works for you.
