### ISSUE TITLE
does not work via "--data-dir" argument 

### ISSUE THREAD

**Issue by Sotonya** [richrobber2/canvas-zoom#59]

**Comment by daswer123** [comment]
Checked it all seems to work, I checked on the local.

https://github.com/richrobber2/canvas-zoom/assets/22278673/3a873e65-a4a5-454b-9742-4c17218431d7

**Comment by daswer123** [comment]
Checked it on the colab, and it really doesn't work with that flag.

BUT, for some reason the javascript folder, which should load automatically in webui, does not. Although install.py works fine. This is most likely a webui flaw.

![image](https://github.com/richrobber2/canvas-zoom/assets/22278673/ef666b7a-ff23-4c65-9572-86aff6040056)

**Comment by Sotonya** [comment]
Maybe it explains something, but I'm not sure: 
![1](https://github.com/richrobber2/canvas-zoom/assets/117153969/a73754ed-35ba-4e8d-ab2b-7876102e2b14)
