### ISSUE TITLE
How about adding the extension to the official list

### ISSUE THREAD

**Issue by daswer123** [richrobber2/canvas-zoom#6]
I thought the extension was quite finished, and I think it's worthy of being on the official extension list.

@richrobber2 do you think it's worth doing?

**Comment by richrobber2** [comment]
yeah, i think its good enough now, where can i do that? @daswer123

**Comment by daswer123** [comment]
Need to make a pull request, https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions
and add the extension to index.json

**Comment by daswer123** [comment]
I can do it if you want.

**Comment by richrobber2** [comment]
> I can do it if you want.

sure that sounds good

**Comment by daswer123** [comment]
Created, now waiting for approval  🙂
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/14
