### ISSUE TITLE
Canvas Zoom doesn't work at all

### ISSUE THREAD

**Issue by exxterixs** [richrobber2/canvas-zoom#63]
I downloaded Canvas zoom through the extentions in SD AUTOMATIC1111. I have the latest version and my gradio is allright. But it still doesn't work. Maybe I have to turn something on in settings? I use Google chrome and when I right click on image in inpaint it just gives out usuall menu. Also none of hotkeys work. I' ve read through the  _https://github.com/richrobber2/canvas-zoom/wiki/Troubleshooting_ and it seems like I have different issue. Maybe you can help me? or direct me to a guide that may help me to solve my problem?
Я если что русский тоже знаю, так что мне можно и на русском объяснить, буду очень благодарен!

**Comment by exxterixs** [comment]
![image](https://github.com/richrobber2/canvas-zoom/assets/135551452/847856c1-916f-4a47-a4eb-a5325a016c83)
Я так раньше туда и не смотрел. оказывается там фатал эроры. Походу я что-то не так установил и надо переустанавливать будет. Ещё и none в hash и  version)

**Comment by daswer123** [comment]
Да, такое часто бывает, возможно были изменены важные файлы и webui не может обновится, лучше всего будет переустановить его.

**Comment by ValeriusSPQR** [comment]
I got the same problem, ever since the update, canvas zoom is no longer working, my gradio version is 3.23.

**Comment by daswer123** [comment]
Hi, send a screenshot of the console where you can see the commit hash, like https://github.com/richrobber2/canvas-zoom/issues/63#issuecomment-1580401900

**Comment by ValeriusSPQR** [comment]
![2023-06-07 16_15_08-Canvas Zoom doesn't work at all · Issue #63 · richrobber2_canvas-zoom](https://github.com/richrobber2/canvas-zoom/assets/135845811/9cb1c165-4ef9-4151-9c45-33aa09ca8036)

Thanks for the quick reply, here the screenshot.

**Comment by ValeriusSPQR** [comment]
That was it, working perfectly now. Thanks so much!
