### ISSUE TITLE
Trojan:Script/ObfusScript.A!ml

### ISSUE THREAD

**Issue by williamkmlau** [richrobber2/canvas-zoom#64]
My windows defender got a "Severe" hit on a js file for canvas zoom:

![image](https://github.com/richrobber2/canvas-zoom/assets/34730446/87be3c57-14da-4dc2-bd5b-96978529f23c)

**Comment by daswer123** [comment]
Lol, this is the first time I've seen a Trojan detected in JS.

This file, as well as the entire templates folder, contains a modified gradio. All that I change is in the js folder, all other files I do not change.

**Comment by daswer123** [comment]
https://github.com/richrobber2/canvas-zoom/issues/65#issuecomment-1583153725
