### ISSUE TITLE
ControlNet tab support?

### ISSUE THREAD

**Issue by joytsay** [richrobber2/canvas-zoom#68]
As for now canvas-zoom is only for the img2img
Sketch, Inpaint, Inpaint sketch tabs,
any support for ControlNet Single Image tab?

**Comment by joytsay** [comment]
#32 Ah so it's not supported yet, 
would be nice if future versions support ControlNet Canvas 
since inpaint outpaint works nice

**Comment by joytsay** [comment]
#32 Ah so it's not supported yet, 
would be nice if future versions support ControlNet Canvas 
since inpaint outpaint works nice

**Comment by daswer123** [comment]
Hi support is already there, you need to enable it in the settings.
You need to have more than 1 unit of controlnet.
https://github.com/richrobber2/canvas-zoom/discussions/42#discussioncomment-6102485
