### ISSUE TITLE
Can't find Canvas Zoom Settings in Automatic1111 Anymore, since the last update

### ISSUE THREAD

**Issue by jem91994** [richrobber2/canvas-zoom#70]
This might just be a me being dumb, but after the last update which changed zoom to Alt+scroll from Shift+scroll, I went to settings to see if I could change back that hotkey but Canvas Zoom is no where to be seen in my settings list. It is definitely still working and installed though since it still works in Inpainting its just the setting tab for this extension appears to be missing? Just me or actual bug?

**Comment by daswer123** [comment]
Try restarting webui and the settings tab will have canvas zoom settings

![image](https://github.com/richrobber2/canvas-zoom/assets/22278673/f54a51c7-ae7a-496c-9148-6394d3965b6c)

**Comment by jem91994** [comment]
After looking into it a bit more, it looks like it doesn't like the call for ".info" from the new config.py file. 

"canvas_hotkey_zoom": shared.OptionInfo("Shift", "Zoom canvas", gr.Radio, {"choices": ["Shift","Ctrl", "Alt"]}).info("If you choose 'Shift' you cannot scroll horizontally, 'Alt' can cause a little trouble in firefox")

The error in my terminal was: AttributeError: 'OptionInfo' object has no attribute 'info'

Error loading script: config.py
Traceback (most recent call last):
  File "C:\sd.webui\webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\sd.webui\webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\sd.webui\webui\extensions\canvas-zoom\scripts\config.py", line 5, in <module>
    "canvas_hotkey_zoom": shared.OptionInfo("Shift", "Zoom canvas", gr.Radio, {"choices": ["Shift","Ctrl", "Alt"]}).info("If you choose 'Shift' you cannot scroll horizontally, 'Alt' can cause a little trouble in firefox"),
AttributeError: 'OptionInfo' object has no attribute 'info'

**Comment by daswer123** [comment]
Hmm, can you show the commit hash in the console?

![image](https://github.com/richrobber2/canvas-zoom/assets/22278673/7abfef60-0e32-46ec-9b54-f8b20f0813b3)

**Comment by jem91994** [comment]
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.2.1
Commit hash: 89f9faa63388756314e8a1d96cf86bf5e0663045
Installing requirements

**Comment by daswer123** [comment]
Bro no problem, if it wasn't for you I wouldn't have known there was a problem. 
I found the problem, the thing is that this property appeared only with version 1.3 and I will try to find an alternative that would make the extension work on older versions.

**Comment by daswer123** [comment]
Released a hotfix, later I will add additional information that I temporarily removed for older versions
