### ISSUE TITLE
Floating Window Extension for Generation Process

### ISSUE THREAD

**Issue by torealise** [richrobber2/canvas-zoom#71]
Can a similar extension be developed to transform the window in which generation occurs into a floating window that can be moved to a second monitor?

можно ли сделать подобный extension который бы превращал окно в котором происходит генерация, в плавающее окно, которое можно перенести на второй монитор?

**Comment by daswer123** [comment]
Не уверен, что такое можно реализовать, это же веб-интерфейс на градио. 
Я думаю как вариант можно придумать что-нибудь через API. 
Но все это вне моей компетенции.
