### ISSUE TITLE
can't change color of mask in "inpainting" mode

### ISSUE THREAD

**Issue by thomaslee101** [richrobber2/canvas-zoom#73]
Hi, i tried to change the color of the mask in "inpainting" tab but I can't find the palette icon at the right upper corner of the window. the hot key "Q" doesn't work too. However when i switch to "inpainting sketch" tab, the palette icon appears and i can change the color of the mask. The hot key "Q" works as well. 

i uploaded the images from my hard drive / PC directly to the "inpainting" panel. i did not generate them from txt2img function.

I am using webui v1.3.2 and gradio 3.29.0 on chrome browser. hope you can solve this issue. thanks very much for your work.

![Screenshot 2023-06-18 235939](https://github.com/richrobber2/canvas-zoom/assets/111881888/9a0c6fc5-843f-4d48-93ae-0a0df563d4b0)
![Screenshot 2023-06-18 235302](https://github.com/richrobber2/canvas-zoom/assets/111881888/91c54a95-feec-408b-b1c5-97b27ea3cfc8)

**Comment by daswer123** [comment]
Hi, thanks for letting me know, I'll try to figure it out

**Comment by daswer123** [comment]
Checked it out, there seems to be no problem.

For some reason it have not installed the modified gradio. Try removing the extension from the extension folder, install it again via webui and restart the console completely.

**Comment by thomaslee101** [comment]
i just reinstalled the extension and it works now! thanks! your extension is a life saver!

![Screenshot 2023-06-19 110934](https://github.com/richrobber2/canvas-zoom/assets/111881888/26ce1b55-a4f7-4211-87d9-1d27b944410a)
