### ISSUE TITLE
After installing the extension, I cannot find the settings

### ISSUE THREAD

**Issue by deviljoker5200** [richrobber2/canvas-zoom#74]
I am using this version of SD. 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/b6af0a3809ea869fb180633f9affcae4b199ffcf
https://github.com/richrobber2/canvas-zoom/commit/ae44f7fba3fcc8d118f8905a0888585dd2728a61

If you are able to use "canvas-zoom" without any issues in the "imgtoimg inpaint" section but want to use it in the "Control Net" section, you need to enable it by checking the appropriate option in the settings.
It's possible that there is a conflict with the Chinese localization version you are using, as you are unable to find "canvas-zoom" in the settings.

**Comment by daswer123** [comment]
I think it's not about localization.

Can you see if you have errors in the console and browser console after webui loads?
