### ISSUE TITLE
【bug】In webui v1.4.0, the "Shift + wheel - Zoom canvas" under ControlNet is not working

### ISSUE THREAD

**Issue by amimi818** [richrobber2/canvas-zoom#79]
[OS]：
Win11/MacOS

[Browser]：
Chrome/Edge

[WebUI]：
AUTOMATIC1111 WebUI v1.4.0

[Description]:
The "Shift + wheel - Zoom canvas" under ControlNet is not working in webui v1.4.0,。But with image2image's inpaint, it works fine.

**Comment by daswer123** [comment]
Hi, make sure that you have controlNet integration enabled in canvas zoom and that the zoom key is set to shift in the settings.

Also try disabling the built-in canvas-zoom-and-pan extension and restarting webui. If that's what's causing it, please let me know

**Comment by daswer123** [comment]
Hi, I tested today and found that as expected. It's because the built-in canvas-zoom-and-pan extension is enabled.
If you disable it, the zoom on controlNet will work. You won't lose anything because the built-in extension is a light version of this.

**Comment by amimi818** [comment]
Thanks for your reply, the problem is perfectly solved！
