### ISSUE TITLE
fix regex to work with any character 

### ISSUE THREAD

**Issue by richrobber2** [richrobber2/canvas-zoom#8]
not sure how to go about that just yet but just thought of it

**Comment by daswer123** [comment]
You mean the extension itself, I think it is easy enough to understand and does not need additional localization.

**Comment by richrobber2** [comment]
more like the buttons, keycodes because of your comment on the readme, saying it only works with English's layout

**Comment by daswer123** [comment]
It's true, by the way, it's worth doing. I'm still looking for a solution.

**Comment by richrobber2** [comment]
i guess we could just do different regex that only checks if it has a character like this

const validKeys = /^.$/;

**Comment by richrobber2** [comment]
instead of checking if it is a number or character

**Comment by daswer123** [comment]
Yes, I think I found a solution, you can get the code of the key and check it, then you can avoid problems with the layout.

function getKeyCode(event) {
  const keyCode = event.keyCode || event.which;
  return keyCode;
}

const hotKeys = {
  65: () => { // Key code "A"
    console.log("A pressed");
  },
  83: () => { // Key code "S"
    console.log("S pressed");
  },
  // Add other hotkeys with corresponding codes
};

function handleKeyPress(event) {
  const keyCode = getKeyCode(event);
  if (hotKeys[keyCode]) {
    hotKeys[keyCode]();
  }
}

**Comment by richrobber2** [comment]
make a pull request im working on the color selector

**Comment by daswer123** [comment]
Ok

**Comment by daswer123** [comment]
Done.

So far only letters, I'll add numbers later.
They are written as: Digit1 and Numpad1 , it is necessary to additionally modify the checking and writing, as well as the output.

**Comment by daswer123** [comment]
Okay, bro, I'm going to bed, I have to work tomorrow, I can work on the project for a while in 1-2 days.

**Comment by richrobber2** [comment]
okay, no problem
