### ISSUE TITLE
T button - unimportant Bug

### ISSUE THREAD

**Issue by alexbabashov** [richrobber2/canvas-zoom#86]
commit: https://github.com/richrobber2/canvas-zoom/commit/be66fb61f52e612dea0b3d6c738c6d5154fb63b5

1.Open the "inpaint" tab.
2.Open an image in the "inpaint" area (drag and drop or file open dialog).
3.Do not move the mouse pointer after opening the image
4.Press the "S" key
5.Do not move the mouse pointer 
6.Press the "T" key
7.Do not move the mouse pointer 

Reality:
opening of the dialog box
"Pin color panel" does not match the cursor position
Note: The cursor is in the center of the screen. There is plenty of space around it for the dialog box

expecting: 
dialog box "Pin color panel" match the cursor position

After any movement of the cursor pointer, everything works correctly.

**Comment by daswer123** [comment]
This is an interesting observation, but I'm not sure if this bug would prevent anyone from working. 

And it happens because the tracking of the cursor and coordinates for the color panel occurs after the picture has appeared and the cursor has made a small movement.
