### ISSUE TITLE
Most of the features don't work in ControlNet until you press Reset or Full screen hotkey

### ISSUE THREAD

**Issue by Rinkashikachi** [richrobber2/canvas-zoom#89]
It is not that severe but it took me like a couple of days to find a workaround.

Extension works fine for me in regular img2img etc.

In ControlNet nothing except brush size and fullscreen mode works until you press reset or activate full screen. Then everything works until you reload the page

Latest canvas-zoom
ControlNet v1.1.234

version: v1.5.1  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0

**Comment by daswer123** [comment]
I found the bug, thanks for telling me.

I'll try to fix it.

**Comment by daswer123** [comment]
All fixed, now all the extension functions should work correctly too
