### ISSUE TITLE
[Errno 2] No such file or directory: 'D:\\sd-webui-aki-v4\\.launcher\\pyinterop.hfkx1kkk0g4q7.zip\\detect_extension.py'

### ISSUE THREAD

**Issue by jasoncow007** [richrobber2/canvas-zoom#90]
*** Error running install.py for extension D:\sd-webui-aki-v4\extensions\canvas-zoom.
*** Command: "D:\sd-webui-aki-v4\py310\python.exe" "D:\sd-webui-aki-v4\extensions\canvas-zoom\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "D:\sd-webui-aki-v4\extensions\canvas-zoom\install.py", line 16, in <module>
***     shutil.copyfile(detect_module_path, destination_path)
***   File "shutil.py", line 254, in copyfile
*** FileNotFoundError: [Errno 2] No such file or directory: 'D:\\sd-webui-aki-v4\\.launcher\\pyinterop.hfkx1kkk0g4q7.zip\\detect_extension.py'

**Comment by daswer123** [comment]
Hi thanks for letting me know,
I've released a quick fix for now, 
I'll look into it more later and do it more properly
