### ISSUE TITLE
Modified gradio is not compatible with gradio 3.41.2

### ISSUE THREAD

**Issue by r0mar0ma** [richrobber2/canvas-zoom#92]
looks like canvas-zoom is breaking automatic webUI 1.6.0 which is using gradio 3.41.2.
it making all values of gradio.Radio() as a tuple.
so instead of "Radio value" we see "Radio value, Radio value" and value of Radio contains a (string, string) instead of string.

**Comment by daswer123** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12886#issuecomment-1701612805

**Comment by daswer123** [comment]
Released a fix, can you check if everything works?

**Comment by r0mar0ma** [comment]
> Released a fix, can you check if everything works?

Looks good now, thanks.
