### ISSUE TITLE
Inpaint Canvas UI broken in A1111 1.6

### ISSUE THREAD

**Issue by madrooky** [richrobber2/canvas-zoom#93]
The functions still work, but as soon as i start painting the canvas UI elements disappear which makes it impossible to work on iterations.

**Comment by daswer123** [comment]
Hello, I will try to fix it soon. You can disable this feature in the settings for now

**Comment by daswer123** [comment]
Hi, I checked and didn't find the problem you mentioned, perhaps there are some errors in the browser console?

https://github.com/richrobber2/canvas-zoom/assets/22278673/b1142af9-771a-4950-a000-e13a4c32ef51
