### ISSUE TITLE
Feature Request: Adjustable Increment for Brush Size Using Ctrl + Mouse Wheel

### ISSUE THREAD

**Issue by richrobber2** [richrobber2/canvas-zoom#95]
Background:
In the current implementation of the brush size adjustment feature (as seen in the adjustBrushSize function), the brush size changes by a fixed percentage of the maximum value. This percentage is currently hardcoded as 5%. While this works well for general use, it lacks flexibility for users who require finer control over brush size adjustments.

Suggested Enhancement:
Introduce a new configuration option in shared.config.py that allows users to specify the percentage increment for adjusting the brush size. This will enable more precise control over the brush size, especially beneficial for detailed artwork or specific use cases.

**Comment by daswer123** [comment]
Hi ,good idea, I think we can add it.

**Comment by daswer123** [comment]
Done, now you can change to any % from 1 to 10.

![image](https://github.com/richrobber2/canvas-zoom/assets/22278673/0c8a69ef-995b-4354-b992-74805afa4839)
